### ISSUE TITLE
Article?

### ISSUE THREAD

**Issue by DeniseSl22** [ZengVera/psoriasis#2]
Dear Vera,

Today, I saw your dataset come by on the [Metabolights website](http://www.ebi.ac.uk/metabolights/MTBLS408). I also found your data upload for supporting data on [GigaDB](http://gigadb.org/dataset/100341). However, I cannot find the article mentioned for this data, and I would like to read it. Could you please help me?

Kind regards,

Denise Slenter
PhD student Maastricht University, the Netherlands.

**Comment by wenbostar** [comment]
Hi Denise @DeniseSl22 

Thanks for your interest in this study. This paper will be online soon. We will let you know when it's online.

Best regards!
Bo

**Comment by wenbostar** [comment]
@DeniseSl22 , this paper is online: https://doi.org/10.1093/gigascience/gix087.

Best regards!
Bo

**Comment by DeniseSl22** [comment]
Ah thank you :) Downloaded it right away. Good that it is open access ;).
